FROM diegogslomp/centos-ssh:8

RUN yum -y update; yum clean all
RUN yum -y install openssh-server openssh-clients passwd sudo python3 python3-psutil git ca-certificates openssl-devel redhat-rpm-config; yum clean all



RUN useradd --create-home -s /bin/bash vagrant
RUN echo -e "vagrant\nvagrant" | (passwd --stdin vagrant)
RUN echo 'vagrant ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/vagrant
RUN chmod 440 /etc/sudoers.d/vagrant

RUN mkdir -p /home/vagrant/.ssh
RUN chmod 700 /home/vagrant/.ssh
ADD https://raw.githubusercontent.com/hashicorp/vagrant/master/keys/vagrant.pub /home/vagrant/.ssh/authorized_keys
RUN chmod 600 /home/vagrant/.ssh/authorized_keys
RUN chown -R vagrant:vagrant /home/vagrant/.ssh

EXPOSE 22 9003
ENTRYPOINT ["/usr/sbin/sshd", "-D"]
